#!/usr/bin/env bash

REP='index.alauda.cn'
NS='niusmallnan'

docker tag python-cicd-demo $REP/$NS/python-cicd-demo
docker login -u niusmallnan -p zzb1988o526 -e 584107985@qq.com $REP
docker push $REP/$NS/python-cicd-demo
docker rmi $REP/$NS/python-cicd-demo
